config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do
    default_url_options :host => "localhost:3000"
    root "static_pages#home"
    get "static_pages/home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users 
    resources :follows do
      member do
        get :follows
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :find_user, :valid_user, :check_expiration,
    only: %i(edit update)

  def new; end

  def create
    @user = User.find_by email: params[:password_reset][:email].downcase
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t("text_repass.send_mail")
      redirect_to root_url
    else
      flash.now[:danger] = t("text_repass.mail_nfound")
      render :new
    end
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, t("users.cant_empty"))
      render :edit
    elsif @user.update user_params
      log_in @user
      flash[:success] = t("users.re_pass")
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def find_user
    @user = User.find_by email: params[:email]
    return if @user
    flash[:danger] = t "n_found"
    redirect_to root_path
  end

  def valid_user
    return redirect_to root_url unless @user&.activated? &&
                                       @user.authenticated?(:reset, params[:id])
  end

  def check_expiration
    return unless @user.password_reset_expired?
    flash[:danger] = t("users.ex_pass")
    redirect_to new_password_reset_url
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, t("text_repass.re_pass") %>
<h1><%=t "text_repass.re_pass" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with scope: @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, t("users.pass")%>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t("users.confirm") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("text_repass.update_pass"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t("text_repass.forgot_pass") %>
<h1><%=t "text_repass.forgot_pass" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with scope: :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.submit t("text_repass.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>