config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do
    default_url_options :host => "localhost:3000"
    root "static_pages#home"
    get "static_pages/home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users 
    resources :follows do
      member do
        get :follows
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("layouts.footer"), "http://www.railstutorial.org/" %>
    <%= link_to "RMichael Hartl", "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("layouts.about"), about_path %></li>
      <li><%= link_to t("layouts.contact"), contact_path %></li>
      <li><%= link_to t("layouts.news"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("static_pages.app_name"), "#", id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t("layouts.home"), root_path %></li>
          <li><%= link_to t("layouts.help"), help_path %></li>
          <% if logged_in? %>
            <li><%= link_to t("users.user"), users_path %></li>
            <li class="dropdown">
              <%= link_to "#", :class=>"dropdown-toggle", :data=>{:toggle=>"dropdown"} do %>
                <%= t("users.account")%> <b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to t("users.profile"), current_user %></li>
                <li><%= link_to t("users.setting"), edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("users.logout"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t("layouts.login"), login_path %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= t("layouts.title") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header"%>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer"%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>